[package]
name = "retina"
version = "0.0.1"
authors = ["Scott Lamb <slamb@slamb.org>"]
license = "MIT/Apache-2.0"
edition = "2018"
keywords = ["rtsp", "multimedia", "video", "streaming", "ip-camera"]
categories = ["network-programming", "multimedia"]
description = "high-level RTSP multimedia streaming library"

[dependencies]
async-stream = "0.3.1"
base64 = "0.13.0"
bitreader = "0.3.3"
bytes = "1.0.1"
digest_auth = "0.3.0"
failure = "0.1.8"
futures = "0.3.14"
hex = "0.4.3"
h264-reader = { git = "https://github.com/scottlamb/h264-reader", branch = "pr-sps-overflow" }
log = "0.4.8"
once_cell = "1.7.2"
pin-project = "1.0.7"
pretty-hex = "0.2.1"
rtcp = "0.2.1"
rtp-rs = "0.5.0"
rtsp-types = { git = "https://github.com/sdroege/rtsp-types" }
sdp = "0.1.3"
smallvec = { version = "1.6.1", features = ["union"] }
time = "0.1.43"
tokio = { version = "1.5.0", features = ["macros", "net", "time"] }
tokio-util = { version = "0.6.6", features = ["codec"] }
url = "2.2.1"

[dev-dependencies]
mylog = { git = "https://github.com/scottlamb/mylog" }
structopt = "0.3.21"
tokio = { version = "1.5.0", features = ["fs", "io-util", "macros", "parking_lot", "rt-multi-thread", "signal"] }
